module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: '#2E8B57',
        'primary-light': '#3CB371',
        'primary-dark': '#228B22',
        accent: '#F4D03F',
        'accent-alt': '#DAA520',
        background: '#FAFAFA',
        surface: '#FFFFFF',
        'course-green': '#2E8B57',
        'fairway': '#90EE90',
        'bunker': '#F4D03F',
        'water': '#3B82F6',
        'out-of-bounds': '#DC2626',
        'birdie': '#16A34A',
        'par': '#3B82F6',
        'bogey': '#F59E0B',
        'double-plus': '#DC2626',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '48px',
        '3xl': '64px',
      },
      borderRadius: {
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
      },
    },
  },
  plugins: [],
};
